/*
 * This file was generated by the NOM IDL compiler for Voyager - DO NOT EDIT!
 *
 *
 * And remember, phase 3 is near...
 */
/*
 * Built from /Users/cinc/svn-sources/nom/trunk/nom/idl/nommethod.idl
 */
#ifndef NOM_NOMMethod_IMPLEMENTATION_FILE
#define NOM_NOMMethod_IMPLEMENTATION_FILE
#endif

#if __OS2__
#define INCL_DOS
#include <os2.h>
#endif /* __OS2__ */

#include <nom.h>
#include <nomtk.h>

#include "nommethod.ih"


/*
 We don˚t precalculate any instance data but just take the pointer to the static method info
 generated by the IDL compiler.
 */
NOMDLLEXPORT NOM_Scope void NOMLINK impl_NOMMethod_initData(NOMMethod* nomSelf,
                                                            const gpointer ptrMethodInfo,
                                                            CORBA_Environment *ev)
{
  NOMMethodData* nomThis = NOMMethodGetData(nomSelf);
  
  _ptrMethodInfo=ptrMethodInfo;
}


NOMDLLEXPORT NOM_Scope NOMString* NOMLINK impl_NOMMethod_getName(NOMMethod* nomSelf,
                                                                 CORBA_Environment *ev)
{
  NOMMethodData* nomThis = NOMMethodGetData(nomSelf);
  NOMString* nomRetval=NOMStringNew();
  nomStaticMethodDesc* ptrMethodDesc=(nomStaticMethodDesc*)_ptrMethodInfo;
  
  if(ptrMethodDesc){
    _assignString(nomRetval, (char*) *ptrMethodDesc->nomMethodId, NULL);
  }
  
  return nomRetval;
}

NOMDLLEXPORT NOM_Scope gpointer NOMLINK impl_NOMMethod_queryMethodToken(NOMMethod* nomSelf,
                                                                        CORBA_Environment *ev)
{
  NOMMethodData* nomThis = NOMMethodGetData(nomSelf);
  gpointer nomRetval=NULL;
  nomStaticMethodDesc* ptrMethodDesc=(nomStaticMethodDesc*)_ptrMethodInfo;
  
  if(ptrMethodDesc){
    return ptrMethodDesc->nomMethod;
  }
  
  return nomRetval;
}

